version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_USER: example-user
      MYSQL_PASSWORD: my_cool_secret
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
    #ports:
      #- "3306:3306"
    volumes:
      - ./mariadb-data/:/var/lib/mysql/
  #httpd:
    #image: httpd:2.4
    #ports:
      #- "8080:80"
    #volumes:
      #- ./public-html/:/usr/local/apache2/htdocs/
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: example-user
      WORDPRESS_DB_PASSWORD: my_cool_secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/:/var/www/html/
